# Generated by Django 2.1.4 on 2018-12-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181208_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('building_num', models.PositiveIntegerField()),
                ('flat_num', models.PositiveIntegerField()),
                ('zip_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=128)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyUser')),
            ],
        ),
    ]
